name: Runs on delete branch
on: delete

jobs:
  delete-with-git-rm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo current branche
        run: git branch --show-current

      - name: Echo github obj
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT