name: Delete dev env on merge to main
on:
  push:
    branches:
      - main
jobs:
  delete-with-git-rm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    
      - name: Remove file with git commit
        run: |
          git rm --ignore-unmatch ./.env.pscale
          if ! git diff-index --quiet HEAD; then
            git commit -am "remove pscale file"
            git push origin main
          fi

