name: Delete dev env on merge to main
on:
  push:
    branches:
      - main
jobs:
  delete-dev-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.env.pscale
  delete-dev-another-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove File 2
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./delete.js

      - name: Content current directory
        run: ls

  delete-with-git-rm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    
      - name: Remove file with git commit
        run: |
          git rm ./.env.pscale
          git commit -am "remove pscale file"
          git push origin main
