name: Delete dev env on merge to main
on:
  push:
    branches:
      - main
jobs:
  delete-dev-config-file:
    runs-on: ubuntu-latest
    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./.env.pscale
